/**
 * Alien bullets.(Items thrown by the enemy when attacking)
 */
public class Rock extends Item {//
    /**
     * There can be a variety of throwing patterns and images
     */
    private int mode = 0;//

    /**
     * Constructor, so that the instance is generated in the corresponding alien position.
     * @param alien a rock start from alien
     * @param panel paint on panel
     */
    Rock(Alien alien, GameArena panel) {
        super(alien.getX(), alien.getY(), "img/icons/Arrow.png", panel);
        this.setSize(0);
    }

    public int getMode() {
        return mode;
    }

    public void setMode(int mode) {
        this.mode = mode;
    }


    /**
     * When mode is 0, it is a normal laser attack When mode is 1, it is a bomb
     * attack by kingAlien
     * Each frame is called to move the instance to the tower at a constant speed.
     * @param panel Game arena needs to update every period.
     */
    public void update(GameArena panel) {
        double alfa;
        int distanceX = getX() - 100;
        int distanceY = -getY() + panel.getHeight() - 250;
        if (distanceY != 0) {
            alfa = Math.atan(distanceX / distanceY);
        } else {
            alfa = 0;
        }
        int dy = (int) (10 * Math.cos(alfa));
        int dx = -(int) (10 * Math.sin(alfa));

        if (distanceY < 0) {
            dy = -dy;
            dx = -dx;
        }
        int toX = getX() + dx;
        int toY;
        if (getY() + dy > 100) {
            toY = getY() + dy;
        } else {
            toY = 100;
        }
        this.setX(toX);
        this.setY(toY);
        if (this.mode == 1) {
            if (this.getY() - panel.tower.getY() < 5) {
                // When the bomb produced by kingAlien is dropped, it will have a shock effect
                // on the tower and cause three additional damage to the tower.
                panel.tower.setHeight(999 * panel.tower.getHeight() / 1000);
                panel.tower.setY(panel.tower.getY() + panel.tower.getHeight() / 1000);
                panel.tower.towerHP(panel.tower.getHp() - 3);
                if (panel.player.getY() >= 2 * (panel.screenSize.height / 3)) {
                    panel.player.setSpeedY(-5);
                    panel.shaking = 5;
                    new Music().play("sound/shaking.wav", false);
                    // When the bomb generated by the instance kingAlien is dropped, the player will
                    // be shocked.
                }
            }
        }
    }


}
